/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GTokenRouteImport } from './routes/g.$token'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth.update-password'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsoleRouteImport } from './routes/_authenticated/console'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedConsoleIndexRouteImport } from './routes/_authenticated/console.index'
import { Route as AuthenticatedPatientsIdRouteImport } from './routes/_authenticated/patients.$id'
import { Route as AuthenticatedGroupsIdRouteImport } from './routes/_authenticated/groups.$id'
import { Route as AuthenticatedConsoleTicketsRouteImport } from './routes/_authenticated/console.tickets'
import { Route as AuthenticatedConsoleSubscribersRouteImport } from './routes/_authenticated/console.subscribers'
import { Route as AuthenticatedConsoleMetricsRouteImport } from './routes/_authenticated/console.metrics'
import { Route as AuthenticatedConsoleInstrumentsRouteImport } from './routes/_authenticated/console.instruments'
import { Route as AuthenticatedAssessmentsIdRouteImport } from './routes/_authenticated/assessments.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GTokenRoute = GTokenRouteImport.update({
  id: '/g/$token',
  path: '/g/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsoleRoute = AuthenticatedConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleIndexRoute =
  AuthenticatedConsoleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedPatientsIdRoute = AuthenticatedPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPatientsRoute,
} as any)
const AuthenticatedGroupsIdRoute = AuthenticatedGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsoleTicketsRoute =
  AuthenticatedConsoleTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleSubscribersRoute =
  AuthenticatedConsoleSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleMetricsRoute =
  AuthenticatedConsoleMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedConsoleInstrumentsRoute =
  AuthenticatedConsoleInstrumentsRouteImport.update({
    id: '/instruments',
    path: '/instruments',
    getParentRoute: () => AuthenticatedConsoleRoute,
  } as any)
const AuthenticatedAssessmentsIdRoute =
  AuthenticatedAssessmentsIdRouteImport.update({
    id: '/assessments/$id',
    path: '/assessments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/console': typeof AuthenticatedConsoleRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/a/$token': typeof ATokenRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/g/$token': typeof GTokenRoute
  '/assessments/$id': typeof AuthenticatedAssessmentsIdRoute
  '/console/instruments': typeof AuthenticatedConsoleInstrumentsRoute
  '/console/metrics': typeof AuthenticatedConsoleMetricsRoute
  '/console/subscribers': typeof AuthenticatedConsoleSubscribersRoute
  '/console/tickets': typeof AuthenticatedConsoleTicketsRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/console/': typeof AuthenticatedConsoleIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/a/$token': typeof ATokenRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/g/$token': typeof GTokenRoute
  '/assessments/$id': typeof AuthenticatedAssessmentsIdRoute
  '/console/instruments': typeof AuthenticatedConsoleInstrumentsRoute
  '/console/metrics': typeof AuthenticatedConsoleMetricsRoute
  '/console/subscribers': typeof AuthenticatedConsoleSubscribersRoute
  '/console/tickets': typeof AuthenticatedConsoleTicketsRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/console': typeof AuthenticatedConsoleIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/console': typeof AuthenticatedConsoleRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/a/$token': typeof ATokenRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/g/$token': typeof GTokenRoute
  '/_authenticated/assessments/$id': typeof AuthenticatedAssessmentsIdRoute
  '/_authenticated/console/instruments': typeof AuthenticatedConsoleInstrumentsRoute
  '/_authenticated/console/metrics': typeof AuthenticatedConsoleMetricsRoute
  '/_authenticated/console/subscribers': typeof AuthenticatedConsoleSubscribersRoute
  '/_authenticated/console/tickets': typeof AuthenticatedConsoleTicketsRoute
  '/_authenticated/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/_authenticated/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/_authenticated/console/': typeof AuthenticatedConsoleIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/audit'
    | '/console'
    | '/dashboard'
    | '/library'
    | '/patients'
    | '/settings'
    | '/a/$token'
    | '/auth/reset'
    | '/auth/update-password'
    | '/g/$token'
    | '/assessments/$id'
    | '/console/instruments'
    | '/console/metrics'
    | '/console/subscribers'
    | '/console/tickets'
    | '/groups/$id'
    | '/patients/$id'
    | '/console/'
    | '/groups/'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/audit'
    | '/dashboard'
    | '/library'
    | '/settings'
    | '/a/$token'
    | '/auth/reset'
    | '/auth/update-password'
    | '/g/$token'
    | '/assessments/$id'
    | '/console/instruments'
    | '/console/metrics'
    | '/console/subscribers'
    | '/console/tickets'
    | '/groups/$id'
    | '/patients/$id'
    | '/console'
    | '/groups'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/audit'
    | '/_authenticated/console'
    | '/_authenticated/dashboard'
    | '/_authenticated/library'
    | '/_authenticated/patients'
    | '/_authenticated/settings'
    | '/a/$token'
    | '/auth/reset'
    | '/auth/update-password'
    | '/g/$token'
    | '/_authenticated/assessments/$id'
    | '/_authenticated/console/instruments'
    | '/_authenticated/console/metrics'
    | '/_authenticated/console/subscribers'
    | '/_authenticated/console/tickets'
    | '/_authenticated/groups/$id'
    | '/_authenticated/patients/$id'
    | '/_authenticated/console/'
    | '/_authenticated/groups/'
    | '/_authenticated/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ATokenRoute: typeof ATokenRoute
  GTokenRoute: typeof GTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$token': {
      id: '/g/$token'
      path: '/g/$token'
      fullPath: '/g/$token'
      preLoaderRoute: typeof GTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console': {
      id: '/_authenticated/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof AuthenticatedConsoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/': {
      id: '/_authenticated/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof AuthenticatedConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/patients/$id': {
      id: '/_authenticated/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AuthenticatedPatientsIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/groups/$id': {
      id: '/_authenticated/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AuthenticatedGroupsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/tickets': {
      id: '/_authenticated/console/tickets'
      path: '/tickets'
      fullPath: '/console/tickets'
      preLoaderRoute: typeof AuthenticatedConsoleTicketsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/subscribers': {
      id: '/_authenticated/console/subscribers'
      path: '/subscribers'
      fullPath: '/console/subscribers'
      preLoaderRoute: typeof AuthenticatedConsoleSubscribersRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/metrics': {
      id: '/_authenticated/console/metrics'
      path: '/metrics'
      fullPath: '/console/metrics'
      preLoaderRoute: typeof AuthenticatedConsoleMetricsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/console/instruments': {
      id: '/_authenticated/console/instruments'
      path: '/instruments'
      fullPath: '/console/instruments'
      preLoaderRoute: typeof AuthenticatedConsoleInstrumentsRouteImport
      parentRoute: typeof AuthenticatedConsoleRoute
    }
    '/_authenticated/assessments/$id': {
      id: '/_authenticated/assessments/$id'
      path: '/assessments/$id'
      fullPath: '/assessments/$id'
      preLoaderRoute: typeof AuthenticatedAssessmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedConsoleRouteChildren {
  AuthenticatedConsoleInstrumentsRoute: typeof AuthenticatedConsoleInstrumentsRoute
  AuthenticatedConsoleMetricsRoute: typeof AuthenticatedConsoleMetricsRoute
  AuthenticatedConsoleSubscribersRoute: typeof AuthenticatedConsoleSubscribersRoute
  AuthenticatedConsoleTicketsRoute: typeof AuthenticatedConsoleTicketsRoute
  AuthenticatedConsoleIndexRoute: typeof AuthenticatedConsoleIndexRoute
}

const AuthenticatedConsoleRouteChildren: AuthenticatedConsoleRouteChildren = {
  AuthenticatedConsoleInstrumentsRoute: AuthenticatedConsoleInstrumentsRoute,
  AuthenticatedConsoleMetricsRoute: AuthenticatedConsoleMetricsRoute,
  AuthenticatedConsoleSubscribersRoute: AuthenticatedConsoleSubscribersRoute,
  AuthenticatedConsoleTicketsRoute: AuthenticatedConsoleTicketsRoute,
  AuthenticatedConsoleIndexRoute: AuthenticatedConsoleIndexRoute,
}

const AuthenticatedConsoleRouteWithChildren =
  AuthenticatedConsoleRoute._addFileChildren(AuthenticatedConsoleRouteChildren)

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsIdRoute: typeof AuthenticatedPatientsIdRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsIdRoute: AuthenticatedPatientsIdRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedConsoleRoute: typeof AuthenticatedConsoleRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAssessmentsIdRoute: typeof AuthenticatedAssessmentsIdRoute
  AuthenticatedGroupsIdRoute: typeof AuthenticatedGroupsIdRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedConsoleRoute: AuthenticatedConsoleRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAssessmentsIdRoute: AuthenticatedAssessmentsIdRoute,
  AuthenticatedGroupsIdRoute: AuthenticatedGroupsIdRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ATokenRoute: ATokenRoute,
  GTokenRoute: GTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
